server:
  bind:
    host: 0.0.0.0
    port: 80
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  language: en-US
  cors: true
  pretty_print: true
  limits:
    default_items: 100
    max_items: 10000
  # templates: /path/to/templates
  map:
    url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
    attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  ogc_schemas_location: /schemas.opengis.net

logging:
  level: ERROR
  #logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: pygeoapi Demo instance - running latest GitHub version
    description: pygeoapi provides an API to geospatial data
    keywords:
      - geospatial
      - data
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/geopython/pygeoapi
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: pygeoapi Development Team
    url: https://pygeoapi.io
  contact:
    name: Kralidis, Tom
    position: Lead Dev
    address: Mailing Address
    city: City
    stateorprovince: Administrative Area
    postalcode: Zip or Postal Code
    country: Canada
    phone: +xx-xxx-xxx-xxxx
    fax: +xx-xxx-xxx-xxxx
    email: you@example.org
    url: Contact URL
    hours: Hours of Service
    instructions: During hours of service.  Off on weekends.
    role: pointOfContact

resources:
  places:
    type: collection
    title: Places
    description: Cities around the world and their DBpedia context
    keywords:
      - sparql
      - pygeoapi
      - rdf
    context:
      - name: schema:name
        description: schema:description
        subjectOf: schema:subjectOf
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: http://dbpedia.org/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - type: feature
        name: pygeoapi_plugins.provider.sparql.SPARQLProvider
        data: /pygeoapi_plugins/tests/data/places.csv
        id_field: index
        geometry:
          x_field: lon
          y_field: lat
        sparql_provider: CSV
        sparql_query:
          endpoint: https://dbpedia.org/sparql
          bind:
            name: uri
            variable: '?subject'
          prefixes:
            '': <http://dbpedia.org/resource/>
            dbpedia2: <http://dbpedia.org/property/>
            dbo: <http://dbpedia.org/ontology/>
          where:
            - subject: '?subject'
              predicate: dbo:populationTotal
              object: '?population'
            - subject: '?subject'
              predicate: dbo:country
              object: '?country'
            - subject: '?subject'
              predicate: '<http://dbpedia.org/property/leaderName>'
              object: '?leader'
          filter:
            - 'FILTER (isIRI(?leader) || (isLiteral(?leader) && (!bound(datatype(?leader)) || datatype(?leader) = xsd:string)))'

  populated:
    type: collection
    title: Populated Places
    description: Populated places, public domain and their DBpedia context
    keywords:
      - sparql
      - pygeoapi
      - rdf
    links:
      - type: text/html
        rel: canonical
        title: information
        href: http://www.naturalearthdata.com/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2011-11-11
        end: null # or empty (either means open ended)
    providers:
      - type: feature
        name: pygeoapi_plugins.provider.sparql.SPARQLProvider
        data: /pygeoapi_plugins/tests/data/ne_110m_populated_places_simple.geojson
        id_field: id
        sparql_provider: GeoJSON
        sparql_query:
          endpoint: https://dbpedia.org/sparql
          bind:
            name: uri
            variable: '?subject'
          where:
            - predicate: 'dbo:populationTotal|dbp:populationCensus'
              object: '?population'
            - predicate: 'dbpedia2:leaderName|dbp:leaderName'
              object: '?leader'
  states:
    type: collection
    title: States
    description: U.S. States and their DBpedia context
    keywords:
      - States
      - Census
    geojsonld: false
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://www.hydroshare.org/resource/3295a17b4cc24d34bd6a5c5aaf753c50/data/contents/states.gpkg
        hreflang: en-US
    extents:
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - type: feature
        name: pygeoapi_plugins.provider.sparql.SPARQLProvider
        data: /pygeoapi_plugins/tests/data/states.gpkg
        id_field: GEOID
        table: states
        sparql_provider: SQLiteGPKG
        sparql_query:
          endpoint: https://dbpedia.org/sparql
          bind:
            name: ' :NAME'
            variable: '?subject'
          where:
            - predicate: dbp:senators
              object: '?senators'
            - predicate: 'dbo:motto|dbp:motto'
              object: '?motto'
            - predicate: dbo:capital
              object: '?capital'
            - predicate: foaf:homepage
              object: '?homepage'
            - predicate: foaf:isPrimaryTopicOf
              object: '?wikipedia_link'
            - predicate: dbp:timezone
              object: '?time_zone'

  reservoirs:
    type: collection
    title: New Mexico Reservoirs
    description: This is a point coverage of dams in the New Mexico, which originally was derived from the national inventory of dams data base (U.S. Army Corps of Engineers, 1982)
    keywords:
      - pygeoapi
      - ckan
      - api
    context:
      - name: schema:name
        description: schema:description
        subjectOf: schema:subjectOf
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://catalog.newmexicowaterdata.org/mn_MN/dataset/new-mexico-reservoirs/resource/08369d21-520b-439e-97e3-5ecb50737887
        hreflang: en-US
    extents:
      spatial:
        bbox: [-109, 31, -103, 37]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - type: feature
        name: pygeoapi_plugins.provider.ckan.CKANProvider
        data: https://catalog.newmexicowaterdata.org/api/3/action/datastore_search
        resource_id: 08369d21-520b-439e-97e3-5ecb50737887
        id_field: _id
        x_field: LONDD
        y_field: LATDD

  intersector:
    type: process
    processor:
      name: pygeoapi_plugins.process.intersect.IntersectionProcessor

  sitemap-generator:
    type: process
    processor:
      name: pygeoapi_plugins.process.sitemap.SitemapProcessor
