# =================================================================
#
# Author: Benjamin Webb <bwebb@lincolninst.edu>
#
# Copyright (c) 2026 Lincoln Institute of Land Policy
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

import logging
import tempfile
from osgeo import gdal, ogr
from typing import Tuple, Any
from zipfile import ZipFile
from pyproj import CRS

from pygeoapi.crs import transform_bbox
from pygeoapi.config import get_config
from pygeoapi.plugin import load_plugin
from pygeoapi.process.base import BaseProcessor, ProcessorExecuteError
from pygeoapi.provider import get_provider_by_type, filter_providers_by_type
from pygeoapi.provider.ogr import GdalErrorHandler
from pygeoapi.util import filter_dict_by_key_value, to_json

LOGGER = logging.getLogger(__name__)

CONFIG = get_config()
COLLECTIONS = filter_dict_by_key_value(CONFIG['resources'], 'type', 'collection')
FEATURE_COLLECTIONS = [
    cid
    for cid, cdef in COLLECTIONS.items()
    if filter_providers_by_type(cdef['providers'], 'feature')
]
FIRST_COLLECTION = next(iter(FEATURE_COLLECTIONS))

PROCESS_DEF = CONFIG['resources']['intersector']
PROCESS_DEF.update(
    {
        'version': '0.2.0',
        'id': 'intersector',
        'title': 'Intersector',
        'description': ('A process that runs an intersection.'),
        'links': [
            {
                'type': 'text/html',
                'rel': 'about',
                'title': 'information',
                'href': 'https://pypi.org/project/pygeoapi-plugins',
                'hreflang': 'en-US',
            }
        ],
        'inputs': {
            'url': {
                'title': {'en': 'Feature URL'},
                'description': {'en': 'URL of valid OGR feature'},
                'keywords': {'en': ['feature', 'url']},
                'schema': {'type': 'string', 'default': None},
                'minOccurs': 0,
                'maxOccurs': 1,
            },
            'file': {
                'title': {'en': 'Feature Data File'},
                'description': {'en': 'Bytes of valid OGR File'},
                'keywords': {'en': ['file', 'data']},
                'schema': {'type': 'string', 'default': None},
                'minOccurs': 0,
                'maxOccurs': 1,
            },
            'collection': {
                'title': {'en': 'Feature Collection'},
                'description': {'en': 'Feature Collection'},
                'keywords': {'en': ['OGC API', 'collection']},
                'schema': {
                    'type': 'string',
                    'example': FIRST_COLLECTION,
                    'enum': FEATURE_COLLECTIONS,
                },
                'minOccurs': 1,
                'maxOccurs': 1,
                'metadata': None,  # TODO how to use?
            },
        },
        'outputs': {
            'path': {
                'title': {'en': 'FeatureCollection'},
                'description': {
                    'en': 'A geoJSON FeatureCollection of the '
                    'path generated by the intersection process'
                },
                'schema': {'type': 'object', 'contentMediaType': 'application/json'},  # noqa
            }
        },
        'example': {
            'inputs': {
                'url': 'https://demo.pygeoapi.io/master/collections/obs/items/238',  # noqa
                'collection': FIRST_COLLECTION,
            }
        },
    }
)


class IntersectionProcessor(BaseProcessor):
    """Intersection Processor"""

    def __init__(self, processor_def):
        """
        Initialize object

        :param processor_def: provider definition

        :returns: pygeoapi.process.intersect.IntersectionProcessor
        """
        LOGGER.debug('IntersectionProcesser init')

        # install error handler
        err = GdalErrorHandler()
        handler = err.handler
        gdal.PushErrorHandler(handler)
        # Exceptions will get raised on anything >= gdal.CE_Failure
        gdal.UseExceptions()

        super().__init__(processor_def, PROCESS_DEF)

    def execute(self, data, outputs=None):
        """
        Execute Intersection Process

        :param data: processor arguments
        :param outputs: processor outputs

        :returns: 'application/json'
        """
        mimetype = 'application/json'
        fc_out = {'type': 'FeatureCollection', 'features': []}

        # Validate input and get feature layer
        collection = self.validate_inputs(data)
        layer, bbox = self.get_layer(url=data.get('url'), file=data.get('file'))

        # Validate input and get provider definition for collection
        provider_def = get_provider_by_type(
            CONFIG['resources'][collection]['providers'], 'feature'
        )
        p = load_plugin('provider', provider_def)

        # Fetch features using bbox of input data
        result = p.query(bbox=bbox, resulttype='hits')
        # Try to determine number of features to fetch
        # if the provider supports it, otherwise default to
        # arbitrary large number to fetch all features in bbox
        hits = result.get('numberMatched', 100000)
        # Handle no features found
        if hits == 0:
            fc_out['numberReturned'] = hits
            LOGGER.info('No features found in collection for provided bbox')
            return mimetype, fc_out

        # Fetch features and insert into output FeatureCollection
        # if they intersect with provided geometry
        features = p.query(bbox=bbox, limit=hits)
        for feature in features['features']:
            geom = ogr.CreateGeometryFromJson(to_json(feature['geometry']))
            if geom and geom.Intersects(layer):
                fc_out['features'].append(feature)

        # Add numberReturned to output and return
        true_hits = len(fc_out['features'])
        fc_out['numberReturned'] = true_hits
        return mimetype, fc_out

    def validate_inputs(self, data) -> str:
        """
        Validate input data

        :param data: processor arguments

        :returns: valid collection_id

        :raises ProcessorExecuteError: if invalid input
        """
        collection = data.get('collection')

        if not data.get('url') and not data.get('file'):
            msg = 'Invalid input, provide either url or feature'
            raise ProcessorExecuteError(msg)

        if data.get('url') and data.get('file'):
            msg = 'Invalid input, provide either url or feature, not both'
            raise ProcessorExecuteError(msg)

        if not collection:
            msg = 'Invalid input: no collection specified'
            raise ProcessorExecuteError(msg)

        if collection not in FEATURE_COLLECTIONS:
            msg = f'Invalid input: collection {collection} not found'
            raise ProcessorExecuteError(msg)

        return collection

    def get_layer(
        self, url: str | None = None, file: Any = None
    ) -> Tuple[ogr.Geometry, list[float]]:
        """
        Private Function: Load feature WKT from URL or bytes of OGR
        like file.

        :param url: URL of feature
        :param feature: feature as string or byte string

        :returns: feature as OGC Layer and WGS84 bbox
        """

        if url:
            # Handle zip and remote files
            if url.startswith('http') and url.endswith('.zip'):
                url = f'/vsizip//vsicurl/{url}'

            # Read feature from URL with GDAL
            try:
                ds = gdal.OpenEx(url, gdal.OF_VECTOR)
                assert ds is not None, 'GDAL could not open feature from URL.'
            except (RuntimeError, AssertionError):
                raise ProcessorExecuteError('GDAL could not open feature.')

            layer = ds.GetLayer()
            srs = layer.GetSpatialRef()

        elif file:
            # Normalize file input to bytes
            if isinstance(file, str):
                file = bytes(file, 'utf-8')
            elif isinstance(file, dict):
                file = bytes(to_json(file), 'utf-8')
            elif not isinstance(file, bytes):
                raise ProcessorExecuteError('Invalid file input')

            # Guess file type in-memory
            file_suffix = ''
            if file[:2] == b'PK':
                file_suffix = '.zip'
            elif file[:4] == b'PAR1':
                file_suffix = '.parquet'

            # Write to temporary file to allow for use of
            # GDAL virtual file systems (e.g. /vsizip/)
            with tempfile.NamedTemporaryFile(suffix=file_suffix) as tmp:
                tmp.write(file)
                tmp.flush()
                tmp_path = tmp.name

                # Handle zipped files using /vsizip/
                if file_suffix == '.zip':
                    with ZipFile(tmp_path, 'r') as zip_ref:
                        [filename] = [
                            f
                            for f in zip_ref.namelist()
                            if f.endswith(('.shp', '.gpkg'))
                        ]
                        tmp_path = f'/vsizip/{tmp_path}/{filename}'

                # Attempt to open file with GDAL
                try:
                    ds = gdal.OpenEx(tmp_path, gdal.OF_VECTOR)
                    msg = f'GDAL could not open feature from file {tmp_path}.'
                    assert ds is not None, msg
                except (RuntimeError, AssertionError):
                    msg = 'GDAL could not open feature.'
                    raise ProcessorExecuteError(msg)

                # Read layer to ensure it persists
                # after temporary file is cleaned up
                layer = ds.GetLayer()
                srs = layer.GetSpatialRef()
        else:
            raise ProcessorExecuteError('No input provided.')

        # Create union of all features in one geometry
        union = ogr.Geometry(ogr.wkbGeometryCollection)
        for feat in layer:
            geom = feat.GetGeometryRef()
            try:
                union.AddGeometry(geom)
            except (ValueError, TypeError):
                raise ProcessorExecuteError('Invalid geometry found.')

        # Attempt to get bbox of layer
        (minx, maxx, miny, maxy) = layer.GetExtent()
        bbox = [minx, miny, maxx, maxy]
        if srs:
            bbox = transform_bbox(bbox, CRS(srs.ExportToWkt()), CRS('EPSG:4326'))

        return (union, bbox)

    def __repr__(self):
        return f'<IntersectionProcessor> {self.name}'
