# =================================================================
#
# Author: Benjamin Webb <bwebb@lincolninst.edu>
#
# Copyright (c) 2026 Lincoln Institute of Land Policy
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

import logging
import tempfile
from osgeo import gdal, ogr
from typing import Tuple
from zipfile import ZipFile
from pyproj import CRS

from pygeoapi.crs import transform_bbox
from pygeoapi.config import get_config
from pygeoapi.plugin import load_plugin
from pygeoapi.process.base import BaseProcessor, ProcessorExecuteError
from pygeoapi.provider.ogr import GdalErrorHandler
from pygeoapi.util import filter_dict_by_key_value, get_provider_default, to_json

LOGGER = logging.getLogger(__name__)

CONFIG = get_config()
COLLECTIONS = filter_dict_by_key_value(CONFIG['resources'], 'type', 'collection')

PROCESS_DEF = CONFIG['resources']['intersector']
PROCESS_DEF.update(
    {
        'version': '0.2.0',
        'id': 'intersector',
        'title': 'Intersector',
        'description': ('A process that runs an intersection.'),
        'links': [
            {
                'type': 'text/html',
                'rel': 'about',
                'title': 'information',
                'href': 'https://pypi.org/project/pygeoapi-plugins',
                'hreflang': 'en-US',
            }
        ],
        'inputs': {
            'url': {
                'title': {'en': 'Feature URL'},
                'description': {'en': 'URL of valid OGR feature'},
                'keywords': {'en': ['feature', 'url']},
                'schema': {'type': 'string', 'default': None},
                'minOccurs': 0,
                'maxOccurs': 1,
            },
            'file': {
                'title': {'en': 'Feature Data File'},
                'description': {'en': 'Bytes of valid OGR File'},
                'keywords': {'en': ['file', 'data']},
                'schema': {'type': 'string', 'default': None},
                'minOccurs': 0,
                'maxOccurs': 1,
            },
            'collection': {
                'title': {'en': 'Feature Collection'},
                'description': {'en': 'Feature Collection'},
                'keywords': {'en': ['OGC API', 'collection']},
                'schema': {
                    'type': 'string',
                    'example': next(iter(COLLECTIONS)),
                    'enum': list(COLLECTIONS),
                },
                'minOccurs': 1,
                'maxOccurs': 1,
                'metadata': None,  # TODO how to use?
            },
        },
        'outputs': {
            'path': {
                'title': {'en': 'FeatureCollection'},
                'description': {
                    'en': 'A geoJSON FeatureCollection of the '
                    'path generated by the intersection process'
                },
                'schema': {'type': 'object', 'contentMediaType': 'application/json'},  # noqa
            }
        },
        'example': {
            'inputs': {
                'url': 'https://demo.pygeoapi.io/master/collections/obs/items/238',  # noqa
                'collection': next(iter(COLLECTIONS)),
            }
        },
    }
)


class IntersectionProcessor(BaseProcessor):
    """Intersection Processor"""

    def __init__(self, processor_def):
        """
        Initialize object

        :param processor_def: provider definition

        :returns: pygeoapi.process.intersect.IntersectionProcessor
        """
        LOGGER.debug('IntersectionProcesser init')

        # install error handler
        err = GdalErrorHandler()
        handler = err.handler
        gdal.PushErrorHandler(handler)
        # Exceptions will get raised on anything >= gdal.CE_Failure
        gdal.UseExceptions()

        super().__init__(processor_def, PROCESS_DEF)

    def execute(self, data, outputs=None):
        """
        Execute Intersection Process

        :param data: processor arguments
        :param outputs: processor outputs

        :returns: 'application/json'
        """
        mimetype = 'application/json'

        if not data.get('url') and not data.get('file'):
            raise ProcessorExecuteError('Invalid input, no Feature to intersect')

        if data.get('url') and data.get('file'):
            raise ProcessorExecuteError(
                'Invalid input, provide either url or feature, not both'
            )

        collection = data.get('collection')
        if not collection:
            raise ProcessorExecuteError('Invalid input: no collection specified')
        elif collection not in COLLECTIONS:
            raise ProcessorExecuteError(
                f'Invalid input: collection {collection} not found'
            )

        layer, bbox = self.get_layer(**data)
        provider_def = get_provider_default(
            CONFIG['resources'][collection]['providers']
        )
        p = load_plugin('provider', provider_def)
        hits = p.query(bbox=bbox, resulttype='hits')['numberMatched']

        if hits == 0:
            msg = 'No features found in collection for provided feature bbox'
            LOGGER.info(msg)
            outputs = {
                'type': 'FeatureCollection',
                'features': [],
                'numberMatched': 0,
                'numberReturned': 0,
            }
            LOGGER.debug('Returning response')
            return mimetype, outputs

        features = p.query(bbox=bbox, limit=hits)

        out_features = []
        for feature in features['features']:
            geom = ogr.CreateGeometryFromJson(to_json(feature['geometry']))

            if geom and geom.Intersects(layer):
                out_features.append(feature)

        outputs = {
            'type': 'FeatureCollection',
            'features': out_features,
            'numberReturned': len(out_features),
        }

        return mimetype, outputs

    def get_layer(
        self, url: str = None, file: bytes = None, with_bbox=False, **kwargs
    ) -> Tuple[ogr.Geometry, Tuple[float]]:
        """
        Private Function: Load feature WKY from URL or bytes of OGR
        like file.

        :param url: URL of feature
        :param feature: feature as string

        :returns: feature as OGC Layer and WGS84 bbox
        """
        if url:
            if url.startswith('http') and url.endswith('.zip'):
                url = f'/vsizip//vsicurl/{url}'

            ds = gdal.OpenEx(url, gdal.OF_VECTOR)
            if ds is None:
                raise ProcessorExecuteError('GDAL could not open feature.')

            layer = ds.GetLayer()
            srs = layer.GetSpatialRef()
        elif file:
            if not isinstance(file, bytes):
                file = bytes(file, 'utf-8')

            # Use /vsistdin/ to read bytes in-memory
            if file[:2] == b'PK':
                ext = '.zip'
            elif file[:4] == b'PAR1':
                ext = '.parquet'
            else:
                ext = ''

            with tempfile.NamedTemporaryFile(suffix=ext) as tmp:
                tmp.write(file)
                tmp.flush()
                tmp_path = tmp.name

                if ext == '.zip':
                    with ZipFile(tmp_path, 'r') as zip_ref:
                        [filename] = [
                            f
                            for f in zip_ref.namelist()
                            if f.endswith(('.shp', '.gpkg'))
                        ]
                        tmp_path = f'/vsizip/{tmp_path}/{filename}'

                ds = gdal.OpenEx(tmp_path, gdal.OF_VECTOR)
                if ds is None:
                    raise ProcessorExecuteError(
                        'GDAL could not open feature from bytes (temp file fallback).'
                    )  # noqa

                layer = ds.GetLayer()
                srs = layer.GetSpatialRef()
        else:
            raise ProcessorExecuteError('No input provided.')

        union = ogr.Geometry(ogr.wkbGeometryCollection)
        for feat in layer:
            geom = feat.GetGeometryRef()
            union.AddGeometry(geom)

        (minx, maxx, miny, maxy) = layer.GetExtent()
        bbox = (minx, miny, maxx, maxy)

        if srs:
            bbox = transform_bbox(bbox, CRS(srs.ExportToWkt()), CRS('EPSG:4326'))

        return (union, bbox)

    def __repr__(self):
        return f'<IntersectionProcessor> {self.name}'
