name: test plugins ⚙️

on: [push, pull_request]

env:
  POSTGRESQL_PASSWORD: ${{ secrets.DatabasePassword || 'postgres' }}

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:14-3.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: ${{ secrets.DatabasePassword || 'postgres' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: 3.12
      - name: Start pygeoapi sitemap instance
        run: |
          docker compose up -d --build &
      - name: Install GDAL with Python bindings
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: gdal-bin libgdal-dev
          add-repository: ppa:ubuntugis/ubuntugis-unstable
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: 'uv.lock'
      - name: Install the project
        run: |
          uv sync --inexact --all-packages --extra dev 
          uv pip install GDAL==`gdal-config --version`
      - name: Setup test data ⚙️
        run: |
          gunzip < tests/data/hotosm_bdi_waterways.sql.gz | psql postgresql://postgres:${{ env.POSTGRESQL_PASSWORD }}@localhost:5432/test
      - name: Run unit tests ⚙️
        env:
          POSTGRESQL_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        run: |
          uv run pytest tests/test_intersect_process.py
          uv run pytest tests/test_geopandas_provider.py
          uv run pytest tests/test_jsonfg_formatter.py
          uv run pytest tests/test_postgresql_provider.py
          uv run pytest tests/test_mvt_postgresql_provider.py
          uv run pytest tests/test_sitemap_process.py
          uv run pytest tests/test_sparql_provider.py
          uv run pytest tests/test_xml_formatter.py
      - name: Failed Tests
        if: failure()
        run: |
          echo "Tests failed. Collecting logs..."
          docker ps -a
          docker logs pygeoapi-plugins-pygeoapi-1
          pip3 freeze
